[package]
name = "wineswap"
version = "0.0.1"
authors = ["WineSeller"]
edition = "2018"
description = "WineSwap, The Concentrated Liquidity"
license = "Apache-2.0"
repository = ""

[dependencies]
cosmwasm-std = { version = "0.16.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw0 = { version = "0.9.1" }
cw20 = { version = "0.9.1" }
cw-storage-plus = { version = "0.9.1" }
terra-cosmwasm = { version = "2.2.0" }