[package]
name = "wineswap-math"
version = "0.0.1"
authors = ["WineSeller"]
edition = "2018"
description = "WineSwap, The Concentrated Liquidity"
license = "Apache-2.0"
repository = ""

[dependencies]
cosmwasm-std = { version = "0.16.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
uint = "0.9.1"
wineswap = { path = "../wineswap", default-features = false, version = "0.0.1"}
